name: Preload NhaDatNet

on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:

jobs:
  preload:
    runs-on: ubuntu-latest
    steps:
      - name: Preload homepage only
        run: |
          curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" "https://nhadatnet.com.vn/"
