name: Preload NhaDatNet

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút
  workflow_dispatch:

jobs:
  preload:
    runs-on: ubuntu-latest
    steps:
      - name: Preload homepage and key category pages
        run: |
          USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
          HEADERS="-H 'Accept-Encoding: gzip, deflate, br' -H 'Cache-Control: max-age=0'"

          URLS=(
            "https://nhadatnet.com.vn/"
            "https://nhadatnet.com.vn/nhu-cau/can-ban/"
            "https://nhadatnet.com.vn/nhu-cau/cho-thue/"
          )

          for url in "${URLS[@]}"; do
            echo "Preloading: $url"
            curl -s -L \
              -A "$USER_AGENT" \
              -H "Accept-Encoding: gzip, deflate, br" \
              -H "Cache-Control: max-age=0" \
              "$url" > /dev/null
          done
